name: yesod-minimal

dependencies:
- base
- yesod-core
- yesod-form
- wai
- warp
- text

executables:
  yesod-minimal:
    main: Minimal
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall

  yesod-minimal-form:
    main: MinimalForm
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
